### ISSUE TITLE
Problems with absolute and relative path

### ISSUE THREAD

**Issue by Priyansh2** [stripathi08/smpost#1]
I ran (python interpreter) your module in my home directory where clone of smpost lies. It gave me following error when i test it with some random text written in both hindi and english. 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/SMPOST/main.py", line 12, in predict
  File "build/bdist.linux-x86_64/egg/SMPOST/main.py", line 33, in test_format
  File "build/bdist.linux-x86_64/egg/SMPOST/rule_transform.py", line 255, in fextract
  File "build/bdist.linux-x86_64/egg/SMPOST/rule_transform.py", line 151, in ngram_extraction
IOError: [Errno 2] No such file or directory: './SMPOST/resources/HI_FN_maxl.p'`

It looks like it is trying to search in the smpost directory (cloned directory) which is not present in the root directory. There's some problem regarding relative and absolute paths of the whole module. Please fix this. 
On the other hand, when i open python interpreter in cloned directory (smpost) it worked correctly. So there is no issue with your code files but only with the path of whole module.

**Comment by stripathi08** [comment]
Thanks a lot for letting me know this @Priyansh2. It has been quite some time that I have seen or updated the module. 
I will make sure to fix the problem - just can't promise that I'll do it right away.
